spring:
  application:
    name: local-bot
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/db;AUTO_SERVER=TRUE;MODE=MySQL;NON_KEYWORDS=VALUE
    username: sa
    password:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  sql:
    init:
      encoding: UTF-8
      mode: always
      data-locations: classpath:sql/init.sql
  h2:
    console:
      enabled: true
      path: /h2-console
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: assign_id
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: true
erupt-app:
  verify-code-count: 1
  reset-pwd: true
  water-mark: false
erupt:
  upload-path: ${run.upload-path:${user.dir}/upload}
  hot-build: false
  upms:
    default-account: admin
    default-password: admin
    expire-time-by-login: 24
  init-method-enum: none
shiro:
  ws:
    server:
      url: /ws/shiro
      enable: true

server:
  tomcat:
    max-http-form-post-size: -1
    max-swallow-size: -1
  port: 8080
run:
  pageSize: 20
  upload-path: ${user.dir}/upload
  napcat-web: "http://127.0.0.1:6099"